CREATE USER db_ref_air_owner WITH PASSWORD 'CHANGEME' NOCREATEDB NOCREATEROLE NOSUPERUSER;
CREATE DATABASE db_ref_air WITH OWNER=db_ref_air_owner ENCODING='UTF8' LC_COLLATE='ru_RU.utf8' LC_CTYPE='ru_RU.utf8' TEMPLATE='template0' CONNECTION LIMIT = -1;
COMMENT ON DATABASE db_ref_air IS 'Database Airline words guide';