--------------------------------------- SEARCH_PATH ---------------------------------------
set search_path = 'air_api';

----------------------------------------- CREATE TABLES -----------------------------------------
do $$
begin

----------------------------- version -----------------------------

DROP TABLE IF EXISTS air_api.version CASCADE;

CREATE TABLE air_api.version (
	version_id bigint PRIMARY KEY GENERATED BY DEFAULT AS identity,
    version text not null,
    description text
);

----------------------------- dictionary -----------------------------

DROP TABLE IF EXISTS air_api.dictionary CASCADE;

CREATE TABLE air_api.dictionary (
    dictionary_id bigint PRIMARY KEY generated BY DEFAULT AS identity,
    abbreviation text UNIQUE NOT NULL,
    original_phrase text
);

COMMENT ON TABLE air_api.dictionary IS 'Словарь';
COMMENT ON COLUMN air_api.dictionary.dictionary_id IS 'Идентификатор аббревиатуры';
COMMENT ON COLUMN air_api.dictionary.abbreviation IS 'Аббревиатура';
COMMENT ON COLUMN air_api.dictionary.original_phrase IS 'Исходное словосочетание';

-------------------- length_constraint ---------------------------------

DROP TABLE IF EXISTS air_api.length_constraint CASCADE;

CREATE TABLE air_api.length_constraint (
	constraint_id bigint PRIMARY KEY generated BY DEFAULT AS identity,
	table_name text NOT NULL,
	field_name text NOT NULL,
	field_length numeric NOT NULL,
	description text NOT NULL
	) ;

COMMENT ON TABLE air_api.length_constraint IS 'Ограничения';
COMMENT ON COLUMN air_api.length_constraint.constraint_id IS 'Идентификатор ограничения';
COMMENT ON COLUMN air_api.length_constraint.table_name IS 'Наименование таблицы';
COMMENT ON COLUMN air_api.length_constraint.field_name IS 'Наименование поля';
COMMENT ON COLUMN air_api.length_constraint.field_length IS 'Максимальная длина поля (количестве символов)';
COMMENT ON COLUMN air_api.length_constraint.description IS 'Описание ограничиваемого поля';

end;
$$;